[theme]
primaryColor="#0b0c0b"
backgroundColor="#f5edec"
secondaryBackgroundColor="#ded2de"
textColor="#202d35"

#[theme]
#primaryColor="#e5f0d9"
#backgroundColor="#000000"
#secondaryBackgroundColor="#39393a"
#textColor="#ecc0d1"